// ============================================
// PHONE HUB STORE — PRODUCT DATA
// Edit this file to update your inventory
// ============================================

const WHATSAPP_NUMBER = '+919876543210'; // Your WhatsApp number (country code + number, no +)

const SAMPLE_PRODUCTS = [
  {
    id: 1,
    name: 'iPhone 13 Pro',
    brand: 'Apple',
    price: 62000,
    condition: 'Used',
    storage: '128GB',
    ram: '6GB',
    batteryHealth: 89,
    category: 'iPhone',
    hotDeal: true,
    available: true,
    image: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-13-pro-silver-select?wid=940&hei=1112&fmt=png-alpha',
    description: 'Excellent condition iPhone 13 Pro with ProMotion display, 3x optical zoom, and powerful A15 Bionic chip. Comes with original box and accessories.',
    specs: {
      'Display': '6.1" Super Retina XDR, 120Hz',
      'Processor': 'Apple A15 Bionic',
      'Camera': '12MP Triple (Main + Ultra + Tele)',
      'Front Camera': '12MP TrueDepth',
      'Battery': '3095 mAh',
      'OS': 'iOS 17',
      'Color': 'Sierra Blue',
      'Face ID': 'Yes',
      '5G': 'Yes',
    },
    addedDate: new Date('2024-12-01'),
  },
  {
    id: 2,
    name: 'Samsung Galaxy S23',
    brand: 'Samsung',
    price: 48000,
    condition: 'Refurbished',
    storage: '256GB',
    ram: '8GB',
    batteryHealth: null,
    category: 'Premium',
    hotDeal: true,
    available: true,
    image: 'https://images.samsung.com/is/image/samsung/p6pim/in/2302/gallery/in-galaxy-s23-s911-sm-s911bzkcins-534863387?$684_547_PNG$',
    description: 'Fully refurbished Samsung Galaxy S23 in pristine condition. Tested and certified by our technicians. 3-month warranty included.',
    specs: {
      'Display': '6.1" Dynamic AMOLED 2X, 120Hz',
      'Processor': 'Snapdragon 8 Gen 2',
      'Camera': '50MP Triple Camera',
      'Front Camera': '12MP',
      'Battery': '3900 mAh',
      'OS': 'Android 14',
      'Color': 'Phantom Black',
      '5G': 'Yes',
    },
    addedDate: new Date('2024-12-05'),
  },
  {
    id: 3,
    name: 'OnePlus 12R',
    brand: 'OnePlus',
    price: 32000,
    condition: 'New',
    storage: '128GB',
    ram: '8GB',
    batteryHealth: null,
    category: 'Android',
    hotDeal: false,
    available: true,
    image: 'https://image01.oneplus.net/ebp/202401/09/1-m00-55-61-rb8bwwwfdpiadzw-aaevqrg7lam706.png',
    description: 'Brand new sealed OnePlus 12R with Snapdragon 8 Gen 1 chipset and massive 5500mAh battery. 100W SuperVOOC charging.',
    specs: {
      'Display': '6.78" AMOLED, 120Hz',
      'Processor': 'Snapdragon 8 Gen 1',
      'Camera': '50MP + 8MP + 2MP',
      'Front Camera': '16MP',
      'Battery': '5500 mAh',
      'Charging': '100W SuperVOOC',
      'OS': 'OxygenOS 14',
      '5G': 'Yes',
    },
    addedDate: new Date('2024-12-10'),
  },
  {
    id: 4,
    name: 'Redmi Note 13',
    brand: 'Xiaomi',
    price: 14500,
    condition: 'New',
    storage: '128GB',
    ram: '6GB',
    batteryHealth: null,
    category: 'Budget',
    hotDeal: false,
    available: true,
    image: 'https://i02.appmifile.com/mi-com-product/fly-birds/redmi-note-13/M00-1E-7D-rB8LB2WjC32AHX0_AABQ2lFVkxA659.png',
    description: 'Best budget phone of 2024! Sharp 108MP camera, 5000mAh battery, and AMOLED display at an unbeatable price.',
    specs: {
      'Display': '6.67" AMOLED, 120Hz',
      'Processor': 'Snapdragon 685',
      'Camera': '108MP + 8MP + 2MP',
      'Front Camera': '16MP',
      'Battery': '5000 mAh',
      'Charging': '33W',
      'OS': 'MIUI 14',
      '5G': 'No',
    },
    addedDate: new Date('2024-12-12'),
  },
  {
    id: 5,
    name: 'iPhone 12',
    brand: 'Apple',
    price: 38000,
    condition: 'Used',
    storage: '64GB',
    ram: '4GB',
    batteryHealth: 82,
    category: 'iPhone',
    hotDeal: false,
    available: true,
    image: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-12-black-select-2020?wid=940&hei=1112&fmt=png-alpha',
    description: 'Good condition iPhone 12 in classic black. Minor scratches on body, screen perfect. Battery at 82%. Original charger included.',
    specs: {
      'Display': '6.1" Super Retina XDR OLED',
      'Processor': 'Apple A14 Bionic',
      'Camera': '12MP Dual (Wide + Ultra)',
      'Front Camera': '12MP',
      'Battery': '2815 mAh',
      'OS': 'iOS 17',
      'Color': 'Black',
      'Face ID': 'Yes',
      '5G': 'Yes',
    },
    addedDate: new Date('2024-11-28'),
  },
  {
    id: 6,
    name: 'Samsung Galaxy A54',
    brand: 'Samsung',
    price: 24999,
    condition: 'New',
    storage: '256GB',
    ram: '8GB',
    batteryHealth: null,
    category: 'Android',
    hotDeal: true,
    available: true,
    image: 'https://images.samsung.com/is/image/samsung/p6pim/in/sm-a546blgdins/gallery/in-galaxy-a54-5g-sm-a546-sm-a546blgdins-534855527?$684_547_PNG$',
    description: 'Brand new Galaxy A54 5G with Exynos 1380, 50MP OIS camera, and IP67 water resistance. Great mid-range value.',
    specs: {
      'Display': '6.4" Super AMOLED, 120Hz',
      'Processor': 'Exynos 1380',
      'Camera': '50MP OIS + 12MP + 5MP',
      'Front Camera': '32MP',
      'Battery': '5000 mAh',
      'Charging': '25W',
      'Water Resistance': 'IP67',
      '5G': 'Yes',
    },
    addedDate: new Date('2024-12-08'),
  },
  {
    id: 7,
    name: 'Realme C55',
    brand: 'Realme',
    price: 9999,
    condition: 'New',
    storage: '64GB',
    ram: '4GB',
    batteryHealth: null,
    category: 'Budget',
    hotDeal: false,
    available: true,
    image: '',
    description: 'Affordable and reliable Realme C55 with a large display and decent camera. Perfect for first-time smartphone users.',
    specs: {
      'Display': '6.72" IPS LCD, 90Hz',
      'Processor': 'Helio G88',
      'Camera': '64MP + 2MP',
      'Front Camera': '8MP',
      'Battery': '5000 mAh',
      'Charging': '33W',
      'OS': 'Realme UI 4.0',
      '5G': 'No',
    },
    addedDate: new Date('2024-12-15'),
  },
  {
    id: 8,
    name: 'iPhone 14 Plus',
    brand: 'Apple',
    price: 74000,
    condition: 'New',
    storage: '128GB',
    ram: '6GB',
    batteryHealth: null,
    category: 'iPhone',
    hotDeal: false,
    available: false,
    image: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-14-plus-blue-select?wid=940&hei=1112&fmt=png-alpha',
    description: 'Latest iPhone 14 Plus with massive 6.7" display and best-in-class battery life. Currently out of stock but can be pre-ordered.',
    specs: {
      'Display': '6.7" Super Retina XDR OLED',
      'Processor': 'Apple A15 Bionic',
      'Camera': '12MP Dual (Main + Ultra)',
      'Front Camera': '12MP TrueDepth',
      'Battery': '4323 mAh',
      'OS': 'iOS 17',
      'Color': 'Blue',
      'Face ID': 'Yes',
      '5G': 'Yes',
    },
    addedDate: new Date('2024-12-14'),
  },
];

const REVIEWS = [
  {
    name: 'Rahul Sharma',
    rating: 5,
    text: 'Bought iPhone 13 Pro from here. Condition is exactly as described. Battery health was 89% as mentioned. Very trustworthy seller!',
  },
  {
    name: 'Priya Verma',
    rating: 5,
    text: 'Got a great deal on Samsung S23 refurbished. They tested everything before handing over. Highly recommended!',
  },
  {
    name: 'Amit Kumar',
    rating: 4,
    text: 'Friendly staff, good pricing, and quick response on WhatsApp. Will definitely buy again.',
  },
  {
    name: 'Sneha Gupta',
    rating: 5,
    text: 'Best phone shop in Bareilly! Got OnePlus 12R at best price. They also gave free screen protector. ⭐⭐⭐⭐⭐',
  },
];
